app:
  name: chaos-platform
  version: 1.0.0
  env: ${APP_ENV:-dev}

server:
  port: ${SERVER_PORT:-8080}
  timeout: 30s
  cors:
    enable: true
    allowOrigins:
      - ${CORS_ORIGIN:-*}

database:
  driver: mysql
  master:
    host: ${DB_HOST:-localhost}
    port: ${DB_PORT:-3306}
  slave:
    - host: ${DB_SLAVE1_HOST}
    - host: ${DB_SLAVE2_HOST}

monitor:
  prometheus:
    enable: true
    port: 9090
  metrics:
    enable: true
    interval: 15s

logging:
  level: ${LOG_LEVEL:-info}
  format: json
  output:
    path: /var/log/chaos-platform
    maxSize: 100
    maxBackups: 3
    maxAge: 7

security:
  jwt:
    secret: ${JWT_SECRET}
    expireHours: 24
  tls:
    enable: false
    certFile: /path/to/cert
    keyFile: /path/to/key

alert:
  enable: true
  providers:
    - type: email
      host: smtp.example.com
      port: 587
      username: your-email
      password: your-password
    - type: dingtalk
      webhook: https://oapi.dingtalk.com/robot/send?access_token=xxx
    - type: webhook
      url: http://your-webhook-url 