apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-platform
  namespace: chaos-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chaos-platform
  template:
    metadata:
      labels:
        app: chaos-platform
    spec:
      containers:
      - name: chaos-platform
        image: chaos-mesh/chaos-platform:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /etc/chaos-platform
      volumes:
      - name: config
        configMap:
          name: chaos-platform-config 